language: go

go:
- 1.10.x

go_import_path: github.com/gemalto/helm-spray

install:

script:
- make dist

deploy:
- provider: releases
  api_key: ${GITHUB_TOKEN}
  file: _dist/helm-spray*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
